#!/bin/bash

MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized

cd $MY_PATH/..
echo $PWD

param=$1
case $param in
  info) vendor/bin/doctrine orm:info;vendor/bin/doctrine orm:validate-schema;;
  create) vendor/bin/doctrine orm:schema-tool:update --force --dump-sql;;
  check) vendor/bin/doctrine orm:ensure-production-settings;;
  cache) vendor/bin/doctrine orm:clear-cache:metadata;vendor/bin/doctrine orm:clear-cache:query;vendor/bin/doctrine orm:clear-cache:result;;
  * ) echo 'params: info, create, check, cache';;
esac

